<?php

use yii2ajaxcrud\ajaxcrud\BulkButtonWidget;
use kartik\grid\GridView;
use yii2ajaxcrud\ajaxcrud\CrudAsset;
use yii\data\ArrayDataProvider;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;
use yii\bootstrap5\Modal;



/** @var yii\web\View $this */
/** @var app\models\ReceiptSponsorFund $model */
$request = Yii::$app->request;
$get = $request->get('sponsor_id');
$rct = $request->get('receipt_sponsor_fund_id');
// dd($rct);
$this->title = $model->description;
$this->params['breadcrumbs'][] = ['label' => 'Student Sponsor', 'url' => ['/fees-management/sm-student-sponsor']];
$this->params['breadcrumbs'][] = ['label' => 'Receipt Sponsor Funds', 'url' => ['/fees-management/receipt-sponsor-fund/index', 'sponsor_id' => $get]];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);

CrudAsset::register($this);
?>
<div class="receipt-sponsor-fund-view">

    <?php
    $session = $model->academic_session; //fetch Academic Session based on session_id
    ?>

    <h1><?php Html::encode($this->title) ?></h1>

    <?php

    // dd($model->countBeneficiaries());

    $am = Yii::$app->db->createCommand('SELECT ROUND(SUM(amount), 2) FROM smis.fss_sponsor_beneficiary where receipt_sponsor_fund_id=' . $model->receipt_sponsor_fund_id)
        ->queryScalar(); //fetch total amount received for this receipt
    if ($model->countBeneficiaries() > 0) {
        $calculations = '
    <i>
    Total Amount given by "' . $model->source_reference . '" = Kshs
    <b class="text-primary">' .
            number_format($model->amount, 2, ".", ",") . ", " .
            '</b>
    </i>
     <i>
        Total Amount Beneficiaries = Kshs
        <b class="text-primary">' .
            number_format($am, 2, ".", ",") . ", " .
            '</b>
    </i>   
    <i>
        Balance = Kshs
        <b class="text-primary">' .
            number_format(($model->amount) - $am, 2, '.', ',') .
            '</b>
    </i>    
    ';
    } else {
        $calculations = '';
    }
    ?>




    <?php
    $beneficiary = Yii::$app->db->createCommand('SELECT * FROM smis.fss_sponsor_beneficiary where receipt_sponsor_fund_id=' . $model->receipt_sponsor_fund_id)
        ->queryAll();

    $am = Yii::$app->db->createCommand('SELECT SUM(amount) FROM smis.fss_sponsor_beneficiary where receipt_sponsor_fund_id=' . $model->receipt_sponsor_fund_id)
        ->queryAll();



    $dataProvider = new ArrayDataProvider([
        'allModels' => $beneficiary,
        // 'pagination' => false,
    ]);




    if ($model->amount > 0 && $model->countBeneficiaries() > 0) {
        $average = ((floatval($model->amount)) / (floatval($model->countBeneficiaries())));
    } else {
        $average = 0;
    }



    ?>

    <div id="ajaxCrudDatatable">
        <?= GridView::widget([
            'id' => 'crud-datatable',
            'dataProvider' => $dataProvider,
            'showPageSummary' => true,
            'panel' => [
                'heading' => '<i class="fas fa-money-bill text-primary"></i>  <b class="text-primary">' . $this->title . '</b>',
                'before' => $calculations,
            ],
            'pjax' => true,
            'exportConfig' => [
                'pdf' => [
                    'label' => 'PDF',
                    'config' => [
                        'methods' => [
                            'SetHeader' => ['Generated By NDU MIS'],
                            'SetFooter' => ['{PAGENO}'],
                        ],
                        'contentBefore' => '<h1 style="text-align: center; font-weight: bold;">' . $this->title . '</h1>',
                        'contentAfter' => '',
                        'options' => [
                            'title' => 'My Customized PDF Export',
                            'subject' => 'My Subject',
                            'keywords' => 'My Keywords',
                        ],
                    ],
                ],
            ],

            'columns' => [
                [
                    'class' => 'kartik\grid\CheckboxColumn',
                    'width' => '20px',
                ],
                [
                    'class' => 'kartik\grid\SerialColumn',
                    'contentOptions' => ['class' => 'kartik-sheet-style'],
                    'width' => '36px',
                    'pageSummary' => 'Total',
                    'pageSummaryOptions' => ['colspan' => 2],
                    'header' => '',
                    'headerOptions' => ['class' => 'kartik-sheet-style']
                ],
                'reg_no',
                'name',
                [
                    'attribute' =>
                    'amount',
                    'pageSummary' => true,
                    'format' => ['decimal', 2],
                ],
                'post_date',
                'user_id',
                'trans_type',
                [
                    'label' => 'Academic Session',
                    'value' => function ($model) use ($session) {
                        $name = Yii::$app->db->createCommand('SELECT acad_session_name FROM smis.org_academic_session WHERE acad_session_id=' . $session)
                            ->queryScalar();
                        return $name;
                    },
                ],

                [
                    'class' => 'kartik\grid\ActionColumn',
                    'dropdown' => false,
                    'noWrap' => 'true',
                    'template' => '{view} {update} {delete}',
                    'vAlign' => 'middle',

                    'urlCreator' => function ($action, $model, $key, $index) use ($get, $rct) {
                        switch ($action) {
                            case 'view':
                                return Url::to([
                                    '/student-records/sponsor-beneficiary/view-cust',
                                    'sponsor_beneficiary_id' => $model['sponsor_beneficiary_id']
                                ]);
                            case 'update':
                                return Url::to([
                                    '/student-records/sponsor-beneficiary/update-cust',
                                    'sponsor_beneficiary_id' => $model['sponsor_beneficiary_id']
                                ]);
                            case 'delete':
                                return Url::to([
                                    '/student-records/sponsor-beneficiary/delete-by-receipt',
                                    'sponsor_beneficiary_id' => $model['sponsor_beneficiary_id']
                                ]);
                            default:
                                return '';
                        }
                    },




                    'viewOptions' => ['role' => 'modal-remote', 'title' => Yii::t('yii2-ajaxcrud', 'View'), 'data-toggle' => 'tooltip', 'class' => 'btn btn-sm btn-outline-success'],
                    'updateOptions' => ['role' => 'modal-remote', 'title' => Yii::t('yii2-ajaxcrud', 'Update'), 'data-toggle' => 'tooltip', 'class' => 'btn btn-sm btn-outline-primary'],
                    'deleteOptions' => [
                        'role' => 'modal-remote', 'title' => Yii::t('yii2-ajaxcrud', 'Delete'), 'class' => 'btn btn-sm btn-outline-danger',
                        'data-confirm' => false,
                        'data-method' => false, // for overide yii data api
                        'data-request-method' => 'post',
                        'data-toggle' => 'tooltip',
                        'data-confirm-title' => Yii::t('yii2-ajaxcrud', 'Delete'),
                        'data-confirm-message' => Yii::t('yii2-ajaxcrud', 'Delete Confirm')
                    ],
                ],


            ],

            'toolbar' => [
                [
                    'content' =>
                    Html::a(
                        '<i class="bi bi-plus-lg"></i> Add Beneficiaries',
                        [
                            'receipt_sponsor_fund_id' => $rct,
                            '/student-records/sponsor-beneficiary/create-receipt', 'sponsor_id' => $get,
                            ['data-pjax' => 1],
                        ],
                        [
                            'class' => 'btn btn-outline-primary',
                            'role' => 'modal-remote',
                            'data-toggle' => 'tooltip',
                        ],
                    ) .
                        Html::a(
                            '<i class="fa fa-plus"></i> Optimize',
                            [
                                'average' => $average,
                                'receipt_sponsor_fund_id' => $rct,
                                '/student-records/sponsor-beneficiary/optimize', 'sponsor_id' => $get,
                                ['data-pjax' => 1],
                            ],
                            [
                                'class' => 'btn btn-outline-success',
                                'role' => 'modal-remote',
                                'data-toggle' => 'tooltip',
                                'data-confirm-title' => 'Optimize',
                                'data-confirm-message' => 'Are you sure you want to optimize?'
                            ]
                        ) .


                        Html::a(
                            '<i class="fa fa-redo"></i>',
                            ['/student-records/receipt-sponsor-fund/beneficiaries', 'sponsor_id' => $get, 'receipt_sponsor_fund_id' => $rct],
                            ['data-pjax' => 2, 'class' => 'btn btn-outline-success', 'title' => Yii::t('yii2-ajaxcrud', 'Reset Grid')]
                        ) .
                        '{toggleData}' .
                        '{export}'
                ],
            ],
        ]) ?>

    </div>
</div>

<?php Modal::begin([
    "id" => "ajaxCrudModal",
    "footer" => "", // always need it for jquery plugin
    "clientOptions" => [
        "tabindex" => false,
        "backdrop" => "static",
        "keyboard" => false,
    ],
    "options" => [
        "tabindex" => false
    ]
]) ?>
<?php Modal::end(); ?>